name: Acquire activation file
on:
  push:
    paths: 
      - 'ProjectSettings/ProjectVersion.txt'

env:
  PROJECT_ROOT: ./
jobs:
  requestManualActivationFile:
    name: Request manual activation file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Unity editor version
        id: getUnityEditorVersion
        uses: CumulusDS/get-yaml-paths-action@v0.1.0
        with:
          file: ${{env.PROJECT_ROOT}}ProjectSettings/ProjectVersion.txt
          versionOutput: m_EditorVersion

      - name: Create manual activation file
        id: createManualLicenseFile
        uses: webbertakken/unity-request-manual-activation-file@v1.1
        with:
          unityVersion: ${{ steps.getUnityEditorVersion.outputs.versionOutput }}

      - name: Expose as artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.createManualLicenseFile.outputs.filePath }}
          path: ${{ steps.createManualLicenseFile.outputs.filePath }}