name: Acquire activation file
on: push
env:
  UNITY_VERSION: 2018.4.20f1
jobs:
  requestManualActivationFile:
    name: Request manual activation file
    runs-on: ubuntu-latest
    steps:
      - name: Create manual activation file
        id: createManualLicenseFile
        uses: webbertakken/unity-request-manual-activation-file@v1.1
        with:
          unityVersion: ${{ env.UNITY_VERSION}}

      - name: Expose as artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.createManualLicenseFile.outputs.filePath }}
          path: ${{ steps.createManualLicenseFile.outputs.filePath }}